source 'https://rubygems.org'

gem 'rails', '3.2.14'
gem "mongoid", "~> 3.0.0"

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'chillout', :path => '../../../'
gem 'jquery-rails'
