source 'https://rubygems.org'

gem 'rails', '5.0.3'
gem 'sqlite3'
gem 'chillout', :path => '../../../'
gem "sidekiq", ENV['SIDEKIQ_VERSION'] || ">= 5"
if ENV['STATE_MACHINES_ACTIVERECORD_VERSION']
  gem "state_machines-activerecord", ENV['STATE_MACHINES_ACTIVERECORD_VERSION']
  gem "state_machines", ENV['STATE_MACHINES_VERSION'] || ENV['STATE_MACHINES_ACTIVERECORD_VERSION']
else
  gem "state_machine", ENV['STATE_MACHINE_VERSION'] || ">= 1.2"
end