source 'https://rubygems.org'

gem 'rails', '4.2.0'
gem 'sqlite3'
gem 'chillout', :path => '../../../'
if Gem::Version.new(RUBY_VERSION) < Gem::Version.new('2.2')
  gem "sidekiq", ENV['SIDEKIQ_VERSION'] || "~> 4.2"
else
  gem "sidekiq", ENV['SIDEKIQ_VERSION'] || ">= 5"
end